version: '3.3'

services:
  redis:
    #image: redis:3.0.6
    image: redis:6.2.4
    ports:
      - '6379:6379'
    expose:
      - 6379
    networks:
      - applicants

  db:
    #image: mysql:5.7
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: 'nodeNestSql'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'Notebook123!'
      MYSQL_ROOT_PASSWORD: 'Notebook123!'
    networks:
      - applicants
    ports:
      - '3306:3306'
    expose:
      - 3306

  app:
    build: .
    ports:
      - 8080:3000
    depends_on:
      - redis
      - db
    networks:
      - applicants

networks:
  applicants:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.128.1.0/24
